### ISSUE TITLE
How does Houdini compare with Relay?

### ISSUE THREAD

**Issue by georgecrawford** [AlecAivazis/houdini#115]
Basic question, but the one feature in particular that I'm chasing is the ability to co-locate the data requirements for a Svelte component inside the component file itself (alongside the JS, HTML and CSS as a first-class citizen). I love the design paradigm this gives, where page or top-of-tree components make the request for the data which will be required by the resulting components. 

As far as I've seen, the two libraries which support this approach, by the means of GraphQL fragments, are Relay and Houdini. I'd love to know the similarities and differences, why Houdini is better, whether Relay works with Svelte kit (not your question to answer, but you might know?), and whether there are any other similar libraries. It'd be a nice addition to the docs, but a quick answer or two here would also be greatly appreciated. 

Thanks!

**Comment by AlecAivazis** [comment]
Hey @georgecrawford - this response got a little longer than I was expecting but hopefully it answers your question 😅 

relay and houdini are the only two graphql clients that I have run into that treat fragments as the core organizational principle. It probably won't come as a surprise to hear that relay was my direct inspiration when building houdini. I started off trying to add relay to a sveltekit project and ran into some problems with the svelte-relay package. It also hadn't been updated in a long while so I decided to just invest the time to build and maintain a relay-like package designed designed with sveltekit in mind. 

I think "better" is a hard thing to label when comparing a very mature library like relay with something that's relatively new. There are some things that houdini gives to the developer which are very tedious if you found a way to use relay with sveltekit (or if you were using urql or apollo with sveltekit). For example, the automatic query hoisting hides a significant amount of boilerplate from the user in every component with a `query`. I'm also quite proud of the list mutation API, i think its dramatically simpler to work with than the imperative APIs that any of the other libraries give you. On top of that, none of the other clients support custom custom scalars in a way that feels 'right'. All of these are a side effect of building off of sapper/sveltekit which have a very closed ecosystem - i can guarantee that the user has a particular build system with a preprocessor API that I can rely on. 

All of that being said, Relay is currently significantly more robust than houdini. This is not just a side effect of its age, but also having a dedicated team at facebook that is responsible for maintaining it. Being connected to such a large company gives them a lot of opportunity for dog-fooding, something that's very hard for a community-driven package to match. Apart from these, relay just has more features than houdini does currently. Houdini is currently missing very basic things like pagination, fragment variables, persisted queries, etc. All of these things are planned for houdini but they're just not there yet. My hope is that I will run into a few people passionate enough about the project to help me grow and maintain it in a sustainable way. 

At the moment, Houdini is just _barely_ passed an MVP for a graphql client. The absolutely necessary features are in place - enough to show my vision for the project. It's going to take some time to get to that `1.0` version but you can see from the roadmap that we are almost over the hump of large things that need to be added. I think once a few more of the basic features are in place, houdini will provide a svelte developer with a significantly smoother experience for building a UI powered by graphql than any of the other libraries that can't assume a particular framework or build system.
