### ISSUE TITLE
Tips for updating to latest version from 0.8.3

### ISSUE THREAD

**Issue by thormuller** [AlecAivazis/houdini#131]
Hi Alec,
After updating to the latest release, I saw that you changed @connection to @list, which I updated accordingly in my code. No other changes were made on my end, but I'm now getting the following error. Before I debug further myself I wanted to see if there were any other changes to the cache object or related handlers that I should know about in your latest work.

```Cannot read property 'id' of undefined
TypeError: Cannot read property 'id' of undefined
    at /$houdini/runtime/cache/cache.js:304:144
    at Array.filter (<anonymous>)
    at Cache._write (/$houdini/runtime/cache/cache.js:304:95)
    at Cache._write (/$houdini/runtime/cache/cache.js:331:26)
    at Cache.write (/$houdini/runtime/cache/cache.js:19:14)
    at Object.writeData (/$houdini/runtime/query.js:73:15)
    at index.svelte:81:35
    at Object.$$render (<APPLICATION_PATH>/node_modules/svelte/internal/index.js:1380:22)
    at Object.default (root.svelte:33:46)
    at eval (<APPLICATION_PATH>/src/routes/__layout.svelte:43:32)
```

**Comment by AlecAivazis** [comment]
Hey @thormuller

Mind sharing the content of the __layout file that’s throwing the error?

**Comment by thormuller** [comment]
sure:

```<script context="module">
	import env from '../environment';
	import { setEnvironment } from '$houdini';

	setEnvironment(env);
</script>

<script>
	import '../global.css';
	import { session } from '$app/stores';
	import { onMount, setContext } from 'svelte';

	import { writable } from 'svelte/store';
	import Header from '$lib/layout/Header.svelte';

	let firebase = writable({});
	let user = null;	
	setContext('firebase', firebase);

	$: user = $session.user || null;

	onMount(async () => {
		window.ssrUser = user;
		const firebaseClient = await import('$services/firebaseClient');
		firebase.set(firebaseClient);
	});

</script>

<Header />
<slot />```

**Comment by AlecAivazis** [comment]
Hm okay must be a different file. How about root.svelte? The error is almost certainly originating from a file with a query

**Comment by thormuller** [comment]
here's index.svelte. note I can see that the query is generating the correct results, but also that the cache does not reflect this:

```
<script context="module" lang="ts">
	export function AllMyRecipesVariables({ session }) {	
		if (!session.authenticated) {
			return this.redirect(302, '/login');
		}
		return {
			id: session.user.id
		};
	}
</script>

<script lang="ts">
	import { myRecipeList } from '$stores/myrecipes';
	import Card from '$lib/myRecipeList/Card.svelte';
	import { query, graphql, AllMyRecipes } from '$houdini';

	const { data } = query<AllMyRecipes>(graphql`
		query AllMyRecipes($id: String!) {
			activeRecipes: queryMyRecipes(id: $id) @list(name: "Active_Recipes") {
				id
				...Card_recipe
			}
		}
	`);

	$: $myRecipeList = $data.activeRecipes;
</script>

<section class="px-4 ">
	{#each $myRecipeList as recipe}
		<Card {recipe} id={recipe.id} />
	{/each}
</section>
```

**Comment by AlecAivazis** [comment]
Thanks for sharing this. I won’t be able to take a look til later today but I’ll let you know when I have an idea of what’s going on. Can you post the query response too?

**Comment by thormuller** [comment]
```
{"activeRecipes":[{"id":"0x2554a94ed","myTitle":"Quick Chickpea and Spinach Curry","klImages":"6e453e05a81ee9707b3f86c7f43cf02e.jpg","domain":"mygoodnesskitchen.com","versions":[null]},{"id":"0x2554a94f4","myTitle":"Roasted Sweet Potato and Spinach Risotto","klImages":"b546b6d3f7170581be6840dd2943345b.jpg","domain":"twopeasandtheirpod.com","versions":[null]}]}
```

**Comment by AlecAivazis** [comment]
Ah, okay. I suspect the problem is that null in the payload. Could you try removing the version field and see if it all works? I’ll get a fix out when I get home tonight.

**Comment by thormuller** [comment]
ah, will do. Thanks for the quick assessment.

**Comment by thormuller** [comment]
I can confirm that removing the field with the null value resolved the issue.

**Comment by AlecAivazis** [comment]
Awesome - thanks for confirming. I'm surprised this used to work, do you remember what your cached id values looked like?

**Comment by AlecAivazis** [comment]
Just opened #132 which should fix this. Thanks again!

**Comment by AlecAivazis** [comment]
This should be fixed in `0.9.5`

**Comment by AlecAivazis** [comment]
Whoops! Didn’t mean to auto-close this. Will keep it open in case you run into more issues with the upgrade 👍

**Comment by thormuller** [comment]
Thanks, all looks good! 

_> Awesome - thanks for confirming. I'm surprised this used to work, do you remember what your cached id values looked like?_

I don't quite remember, but in the old version I _was_ seeing strange behavior (though it didn't throw this particular error) that now makes sense. To wit: If I had two records, where one of those fields had a value, and the other was null, the cache would first reflect the value and then update, replacing them all as null. That strange behavior is one reason I updated Houdini.

**Comment by AlecAivazis** [comment]
fantastic! thanks for being patient
