### ISSUE TITLE
Add hook for executing logic at the beginning of load

### ISSUE THREAD

**Issue by AlecAivazis** [AlecAivazis/houdini#147]
A user might want to perform additional logic in the generated load function. One example brought up by @pixelmund was to ensure that the user was authenticated a perform and perform a redirect if not. We might want to explore adding a life cycle method that we can invoke in the generated `load`. 

Another option might be to bring back some old code that tried to inject the `load` logic into an existing function. This approach is dramatically more complicated to implement but also allows the user to add additional loading logic that might not fit within their graphql api

**Comment by benbender** [comment]
Just as a note, you might want to have a look on the pipeline-system of blitzjs. It's really great, because it's quite flexible and the type inferrence is cake!
-> https://blitzjs.com/docs/resolver-server-utilities

**Comment by AlecAivazis** [comment]
Maybe i'm missing something - is this related to the lifecycle of the load somehow?

**Comment by benbender** [comment]
Maybe I missunderstood, the context of the idea, but in blitz the system is used as a flexible pipeline to authenticate/validate/modify/whatever mutations/queries. The beauty is the flexibility and the inherent type-safety without extra-cost. I assumed you were talking about the lifecycle of a request, because thats the context where authentication matters...

**Comment by AlecAivazis** [comment]
Ah gotcha, I mostly just meant to have a way for the user to define logic that will fire before the generated loader does its thing. For example, pixelmund was using a variable function that always returned the same value to fill this role:

```
     export function NotesVariables(this: RequestContext): any {
        if (!this.context.session.session.id) {
            return this.redirect(302, '/auth/sign-in');
        }
        if (this.context.session.session.authType === 'verification') {
            return this.redirect(302, '/auth/verification');
        }

        return {
            first: 7,
        };
    } 
```

This clearly doesn't need to be a variable and could instead be hard coded in the query body but there's no way for him to add a little bit of logic to check the sveltekit session before the load. My hope was to add a hook (probably better word than lifecycle) that lets the user do something like this
