### ISSUE TITLE
Error unwrapping list of lists

### ISSUE THREAD

**Issue by SorenHolstHansen** [AlecAivazis/houdini#150]
I have created a graphql schema which I have boiled down to this
```graphql
type SomeQuery {
    title: String
    failingField: [[String!]!]
}
```

Now, when I try and fetch this on the front end, I get the following error

```
TypeError: Cannot read property 'value' of undefined
    at unwrapType (file:///.../node_modules/houdini/build/cmd.js:73765:53)
    at inlineType (file:///.../node_modules/houdini/build/cmd.js:76263:14)
    at file:///.../node_modules/houdini/build/cmd.js:76315:33
    at Array.map (<anonymous>)
    at inlineType (file:///.../node_modules/houdini/build/cmd.js:76308:132)
    at file:///.../node_modules/houdini/build/cmd.js:76315:33
    at Array.map (<anonymous>)
    at inlineType (file:///.../node_modules/houdini/build/cmd.js:76308:132)
    at file:///.../node_modules/houdini/build/cmd.js:76315:33
    at Array.map (<anonymous>)
```
But if I leave out the `failingField` field, the query succeeds. I am not sure if this is an issue with Houdini, or I am doing something wrong

**Comment by AlecAivazis** [comment]
oo the list of lists is for sure to blame - Ill work on getting a fix out tonight

**Comment by AlecAivazis** [comment]
@SorenHolstHansen - i have half of the problem fixed. Will work on the rest of it later today. You can track the progress in #151

**Comment by AlecAivazis** [comment]
Have all of the tests for the other half passing. Was a lot trickier than I expected but it's done now. Will review it and hopefully have it deployed tomorrow morning

**Comment by AlecAivazis** [comment]
This should be fixed now - let me know if you are still running into problems

**Comment by SorenHolstHansen** [comment]
Thanks man! You are a wizard
