### ISSUE TITLE
houdini generate -p throws error if schema file doesn't exist

### ISSUE THREAD

**Issue by ledesmablt** [AlecAivazis/houdini#162]
Use case: I want to run the `generate` command in CI and I don't want to commit the `$houdini` folder and `schema.graphql` file to minimize clutter from generated files in my repo.

I already have an existing `houdini.config.js` file. When I run `houdini generate -p`, I'd expect it to pull the latest schema regardless of whether or not an existing schema file exists. Instead, if the schema file doesn't exist, it gives me this message:

```
(node:25587) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open
 '/Users/benj/projects/preview-app/schema.graphql'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at new Config (file:///Users/benj/projects/preview-app/node_modules/houdini/build/cmd.js:
689:64)
    at file:///Users/benj/projects/preview-app/node_modules/houdini/build/cmd.js:1048:31
    at step (file:///Users/benj/projects/preview-app/node_modules/houdini/build/cmd.js:346:23
)
    at Object.next (file:///Users/benj/projects/preview-app/node_modules/houdini/build/cmd.js
:327:53)
    at fulfilled (file:///Users/benj/projects/preview-app/node_modules/houdini/build/cmd.js:3
17:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25587) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error origin
ated either by throwing inside of an async function without a catch block, or by rejecting a
promise which was not handled with .catch(). To terminate the node process on unhandled promi
se rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cl
i.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25587) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In th
e future, promise rejections that are not handled will terminate the Node.js process with a n
on-zero exit code.
✨  Done in 0.25s.
```

I suspect that this is caused by the `getConfig()` function depending on the schema file already existing ([see code](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini-common/src/config.ts#L92-L103)). I understand that `houdini init` creates this file, but when running the whole thing in CI I'd want a way to automatically create the schema file since `init` requires user input through the houdini CLI.

I think either tweaking `generate -p` to not throw that error or adding a separate command to only pull the schema file (assuming that a config file already exists) would do the trick. But also explicitly stating in the README that the `schema.graphql` file should be committed for the whole thing to work is fine in case those above suggestions don't make sense.

Now, I've decided to commit the `schema.graphql` file and everything's working fine again. Ideally though I'd want to keep all auto-generated files out of my repo, but I can work with this setup for now. Just raising all these issues for your awareness and in case someone else might run into the same problem.

P.S. (related problem) The houdini preprocessor also depends on `schema`. This is a problem if the user runs the graphql endpoint on the same sveltekit project and gets the steps mixed up and adds the preprocessor to the sveltekit config file before running init + generate. It basically throws the same file not found error and fails to render anything including the `/graphql` endpoint. Would be great to throw an error in the preprocessor telling the user explicitly to run `init` commands before adding the preprocessor, or to at least explicitly state this dependency in the readme.

Btw thanks for this awesome library!!

**Comment by AlecAivazis** [comment]
I think you're right that the best way to address this is to tweak `generate -p` works if there's no schema file. If you want to try to fix that, i would love to review a PR. Otherwise I'll get to it once i finish up a few other small tasks.

in regards to your comment about the preprocessor, I've been going back and forth on the best way to address this issue. Where I'm currentlly at is to have the preprocessor be generated with the rest of the runtime. This would not only force the user to have executed `init` (or generate) before they can do anything but would also simplify the installation process since there would only be one package to install. It would also avoid a common source of pain where users forget to upgrade one package and not the other.

**Comment by ledesmablt** [comment]
I'd be happy to try my hand at a PR for the `generate -p` fix! =)

Also I think your approach for the preprocessor makes sense, though I haven't given a lot of thought to it yet so am not sure if there's a better approach.

**Comment by AlecAivazis** [comment]
Closing this since #165 is merged
