### ISSUE TITLE
preprocessor error when querying from load function

### ISSUE THREAD

**Issue by ledesmablt** [AlecAivazis/houdini#163]
Other houdini queries are working just fine, but when I try querying from inside the load function in SvelteKit it throws this error below.

```
Error: Looks like you don't have the preprocessor enabled.
    at Module.graphql (/$houdini/runtime/index.js:21:11)
    at eval (/Users/benj/projects/preview-app/src/routes/u/[sellerUsername].svelte:69:77)
    at Generator.next (<anonymous>)
    at eval (/Users/benj/projects/preview-app/src/routes/u/[sellerUsername].svelte:59:66)
    at new Promise (<anonymous>)
    at __awaiter (/Users/benj/projects/preview-app/src/routes/u/[sellerUsername].svelte:36:9)
    at load (/Users/benj/projects/preview-app/src/routes/u/[sellerUsername].svelte:65:28)
    at load_node (file:///Users/benj/projects/preview-app/node_modules/@sveltejs/kit/dist/ssr.js:864:30)
    at respond$1 (file:///Users/benj/projects/preview-app/node_modules/@sveltejs/kit/dist/ssr.js:1136:21)
    at async render_page (file:///Users/benj/projects/preview-app/node_modules/@sveltejs/kit/dist/ssr.js:1290:20)
```

My svelte.config.js file:
```
import preprocess from 'svelte-preprocess'
import houdini from 'houdini-preprocess'
import node from '@sveltejs/adapter-node'
import path from 'path'

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: [preprocess({ postcss: true }), houdini()],

  kit: {
    // hydrate the <div id="svelte"> element in src/app.html
    target: '#svelte',
    adapter: node(),
    vite: {
      resolve: {
        alias: {
          $houdini: path.resolve('.', '$houdini')
        }
      }
    }
  }
}

export default config
```

The load function (please let me know if I'm using this wrong):
```
<script lang="ts" context="module">
  import type { Load } from '@sveltejs/kit'
  import { query, graphql } from '$houdini'
  export const load: Load = async ({ page }) => {
    const username = page.params.sellerUsername
    try {
      const { data } = query(graphql`
        ... query data
      `)
      const seller = data.get_seller
      return {
        props: {
          seller
        }
      }
    } catch (err) {
      console.log(err)
      return {
        status: 400,
        error: new Error(err[0].message)
      }
    }
  }
</script>
```

**Comment by AlecAivazis** [comment]
Hey @ledesmablt  - sorry to hear you are running into some issues. 

The query function isn't meant to be inside of a load function as you have it. The preprocessor only looks inside of the instance scripts to replace the `graphql` tag. The idea is that you shouldn't have to worry about defining your `load` function, and threading the value to your components props - the preprocessor takes care of that for you.

Can you give me some more information about what you're trying to accomplish?

**Comment by pixelmund** [comment]
This is not how Houdini works. Houdinis preprocessor automatically transforms your query into the load function. [https://github.com/AlecAivazis/houdini#what-about-load](https://github.com/AlecAivazis/houdini#what-about-load)

**Comment by ledesmablt** [comment]
> Can you give me some more information about what you're trying to accomplish?

@AlecAivazis I was thinking that instead of calling `fetch` from the sveltekit load function, I could use `query` instead (which I probably misunderstood from [this section](https://github.com/AlecAivazis/houdini#what-about-load)).

Here's my original implementation with `fetch`, which I was hoping to transfer to `query` instead.

```
<script lang="ts" context="module">
  import type { Load } from '@sveltejs/kit'
  export const load: Load = async ({ page, fetch }) => {
    const username = page.params.sellerUsername
    const res = await fetch('/graphql', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        variables: { username, fromShop: true },
        query: `query ($username: String!, $fromShop: Boolean!) {
          ... query data
        }`
      })
    }).then((r) => r.json())
    if (res.errors) {
      return {
        status: 400,
        error: new Error(res.errors[0].message)
      }
    }
    const seller = res.data.get_seller
    if (!seller) {
      return {
        status: 404,
        error: new Error(`Seller ${username} not found`)
      }
    }
    return {
      props: {
        seller
      }
    }
  }
</script>
```

**Comment by AlecAivazis** [comment]
Ah great! Well the good news is that this is exactly what the preprocessor will turn a normal query into without you having to worry about it. 

It sounds like you've seen `query` work in a normal `script` tag, right? If so, that's all you need to do - you don't have to define `load`, the preprocessor will generate that for you if you defined your query inside of a component under `src/routes/...`.  To make this concete, all you need to do for the situation you shared is define your component like the following, and let houdini take care of the rest:

```svelte
<script>
    const { data } = query(graphql`
        ... queryData
    `)
</script>

{$data.value}
```

I do see that you are trying to pass variables to your query. In which case the API looks like the following. I know it feels a bit awkward to have a `context="module"` but rest assured there are good reasons :) You'll also have to give your query a name in order for the document generation to work (this is always true, not just if there are variables for your query)

```svelte
<script>
    const { data } = query(graphql`
        query MyQuery ($username: String!, $fromShop: Boolean!) {
          ... query data
        }
    `)
</script>

<script context="module">
    function MyQueryVariables({ page }){ 
        return { 
            username: page.params.sellerUsername,
            fromShop: true,
        }
    }
</script>


{$data.value}
```

**Comment by ledesmablt** [comment]
Thank you so much for the clear explanation! I've implemented it following your suggestion and it works as expected. Appreciate that you took the time to write out examples.

Sorry for the misunderstanding, I tunnel visioned into expecting it to behave like react apollo's `useQuery` (fires after pageload). It wasn't clear to me that `query` calls defined in a non-module `<script>` block would be moved into SvelteKit's load function.
