### ISSUE TITLE
Error: Could not convert scalar type: Date

### ISSUE THREAD

**Issue by cyouiku-94** [AlecAivazis/houdini#167]
I am new to svelte and graphql, when I query a date param, error ocurres. Can you help?

**Comment by pixelmund** [comment]
Hey did you setup the Date custom Scalar in your Houdini config? Like described here [https://github.com/AlecAivazis/houdini#%EF%B8%8Fcustom-scalars](https://github.com/AlecAivazis/houdini#%EF%B8%8Fcustom-scalars)

**Comment by cyouiku-94** [comment]
I missed it, but after I had added this, the error still occured.
`/** @type {import('houdini').ConfigFile} */
const config = {
	schemaPath: './schema.graphql',
	sourceGlob: 'src/**/*.svelte',
	module: 'esm',
	framework: 'kit',
	apiUrl: 'http://localhost:1337/graphql',
	scalars: {
		DateTime: {
			type: 'Date',
			marshal(val) {
				return val.getTime()
			},
			unmarshal(val) {
				return new Date(val)
			},
		},
	},
}

export default config



`

**Comment by pixelmund** [comment]
Can you share your graphql schema?

**Comment by cyouiku-94** [comment]
Is this ok?
[schema.txt](https://github.com/AlecAivazis/houdini/files/7036609/schema.txt)

**Comment by AlecAivazis** [comment]
Hey @cyouiku-94! Mind sharing the error you get?

**Comment by cyouiku-94** [comment]
thanks, somewhere else has error. close OK
