### ISSUE TITLE
Running a valid query returns data as 'undefined'

### ISSUE THREAD

**Issue by bigpodio** [AlecAivazis/houdini#176]
I run Hasura CE. In the console I can successfully perform the following query: 

```
query AllItems{
  tester_test {
    id
    name
  }
}
```

Which with returns data as follows:

```json
{
  "data": {
    "tester_test": [
      {
        "name": "Kevin",
        "id": 1
      }
    ]
  }
}
```

In my SvelteKit project, using Houdini, I have the following index.svelte file:

```javascript
<script>
    import { query, graphql, AllItems } from '$houdini'
    import { navigating } from '$app/stores'

    const { data } = query<AllItems>(graphql`
           query AllItems{
              tester_test{
                 id
                 name
              }
           }
    `)

</script>

{#if $navigating}
    loading...
{:else}
    data is loaded!
    {#if {$data}}
       {$data.length}
    {/if}
{/if}
```

However, when I run the app it shows {$data} as undefined. No errors are thrown anywhere. 

This looked to me that it should be fairly straightforward. Am I missing something?

**Comment by pixelmund** [comment]
Hey, i think you should do `{#if $data}` not `{#if {$data}}` also it would be `$data.tester_test.length`

**Comment by AlecAivazis** [comment]
Thanks @pixelmund!

@bigpodio any updates on your side? I'd like to close this issue if its not a problem any more

**Comment by AlecAivazis** [comment]
I'm going to close this since its gone stale - @bigpodio feel free to let us know if its still a problem we can investigate
