### ISSUE TITLE
Getting access to the error on mutations

### ISSUE THREAD

**Issue by SorenHolstHansen** [AlecAivazis/houdini#180]
It would be nice to get access to the error on mutations like on queries.
Maybe it can be something like this
```
let callMutation = mutation<SomeMutation>(graphql`
mutation SomeMutation {
  ...
}
`)
let { error, data } = await callMutation();
```

Or am I missing something, and we already can?

**Comment by AlecAivazis** [comment]
If there is an error returned by your API, it should be thrown as an exception when invoking `callMutation` in your example. So if you want to do something with the error you can do something like:

```
try { 
    callMutation().
}  catch ( error )  {
    console.log(error)
}
```

**Comment by SorenHolstHansen** [comment]
Yeah, okay, hadn't though about that 😅
