### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by lberezy** [AlecAivazis/houdini#197]
I've used the `async-graphql` and `axum` crates to implement a toy GraphQL endpoint in Rust. I have it running locally at `http://localhost:300/` and it works just fine when I interact with it using GraphQL Playground.

However, when I try to point houdini at it, I hit the following issue:

```
npx houdini generate --pull-schema
Pulled latest schema from http://localhost:3001/
TypeError: Cannot read properties of undefined (reading 'type')
    at Object.Field (file:///home/user/.npm/_npx/754cf465adfd4c79/node_modules/houdini/build/cmd.js:76008:70)
    at Module.visit (/home/user/.npm/_npx/754cf465adfd4c79/node_modules/graphql/language/visitor.js:243:26)
    at file:///home/user/.npm/_npx/754cf465adfd4c79/node_modules/houdini/build/cmd.js:75996:44
```

Unsure what the issue is, although [this example project](https://github.com/skrenes/houdini-kit) mentions something about the a lack of support in the endpoint for websockets/subscriptions. My endpoint doesn't use subscriptions, with the schema being simply:

```graphql
schema {
  query: QueryRoot
  mutation: MutationRoot
}

"""Directs the executor to query only when the field exists."""
directive @ifdef on FIELD

type Model {
  id: Int!
  name: String!
  related: [Model!]!
}

type MutationRoot {
  new(item: NewModel!): Boolean!
}

input NewModel {
  name: String!
}

type QueryRoot {
  item(id: Int!): Model
}
```

I'm unsure what the error message is really telling me here and wanted to raise this also if anyone else is having the same issue.

**Comment by AlecAivazis** [comment]
Hey @lberezy - sorry you're runing into this. I'm pretty sure the issue in the package you linked to has been fixed but like you said it's unlikely that it's related to what you're experiencing. 

Can you share your component's query/fragment?

**Comment by lberezy** [comment]
Okay I've figured it out, and it's largely user error on my part.

I got a bit ahead of myself and had already built a query that didn't match the schema (a typo in the object/field name), which I forgot about. I didn't realize at the time that this was the issue as the order of steps in the intro doco are for the case where you presumably haven't written any query/fragment and running `npx houdini generate --pull-schema` will just work.

Fixing that up solved my issue. It would be nice however to provide a slightly more descriptive error message if at all possible.

**Comment by AlecAivazis** [comment]
Ah okay cool - i'm going to go ahead and close this then. Do you mind sharing the query so I can see if I can figure out why the validators didn't catch it?

**Comment by lberezy** [comment]
Sure thing, thanks for closing it.

The query was

```graphql
query GetItemQuery($id: Int!) {
			items(id: $id) {
				id
				name
			}
		}
```

Note that `items` should have been `item`.

If I typo a property/field name inside that structure the error messages are super helpful, it's just real confusing if you get the object name wrong without realizing.
