### ISSUE TITLE
Svelte-Kit erroring that the preprocessor is not enabled

### ISSUE THREAD

**Issue by mzztin** [AlecAivazis/houdini#201]
Error: ```500
Looks like you don't have the preprocessor enabled.
Error: Looks like you don't have the preprocessor enabled.
    at Module.graphql (/$houdini/runtime/index.js:12:11)
    at eval (/src/lib/queries/login.ts:5:61)```
and my config is 
```js
import { optimizeImports } from "carbon-preprocess-svelte";
import path from "path";
import houdini from "houdini-preprocess";
import preprocess from 'svelte-preprocess'

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [houdini(), preprocess(), optimizeImports()],
	kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		target: "#svelte",
		vite: {
			server: {
				fs: {
				  allow: ['..']
				}
			  },
			resolve: {
                alias: {
                    $houdini: path.resolve('.', '$houdini')
                }
            }
		}
	}
};

export default config;
```

anyone knows why this happens?

**Comment by mzztin** [comment]
Now I mangaged to get it to work but I am getting the error `Uncaught (in promise) SyntaxError: The requested module '/$houdini/index.js' does not provide an export named 'SubscriptionHandler'
async function (async)
start @ start.js:1207
(anonymous) @ login:18` anyone knows what this is about?

**Comment by AlecAivazis** [comment]
Hey @mzztin - good to hear you got  your original issue fixed, do you mind sharing what the source of confusion was so i can clarify the documentation?

Also, the best way to address the type issue you are running into is to move the import for `SubscriptionHandler` to a `import type` statement:

```
import type { SubscriptionHandler } from '$houdini' 
```

**Comment by vhscom** [comment]
Issue occurs when user attempts query from `context="module"` script. This could happen if, for example the user reads FAQ and learns queries use `load` and assumes query should be placed in load. If user studies documented examples, they should notice this although an explicit callout might help.

**Comment by vhscom** [comment]
Issue occurs when user attempts query from `context="module"` script. This is likely to occur during refactoring or if the user does not study existing documented examples carefully enough.

**Comment by vhscom** [comment]
Issue occurs when user attempts to query from `context="module"` script. This is likely to occur as users are refactoring existing load functions or if they read the FAQ where it explains `load` functions are generated then assume their queries should be placed in the same location within their layouts/routes.

**Comment by vhscom** [comment]
Issue occurs when user attempts to query from `context="module"` script. This is likely to occur as users are refactoring existing load functions or if they read the FAQ where it explains `load` functions are generated then assume their queries should be placed in the same location.

**Comment by vhscom** [comment]
> do you mind sharing what the source of confusion was so i can clarify the documentation?

Issue occurs when user attempts to query from context="module" script. This is likely to occur as users are refactoring existing load functions or if they read the FAQ where it explains load functions are generated then assume their queries should be placed in the same location.

**Comment by vhscom** [comment]
> do you mind sharing what the source of confusion was so i can clarify the documentation?

Issue occurs when user attempts to query from `context="module"` script. This is likely to occur as users are refactoring existing load functions or they do not pick up on this subtlety while reading the FAQ.
