### ISSUE TITLE
[Feature] query data in onLoad hook

### ISSUE THREAD

**Issue by ximus** [AlecAivazis/houdini#202]
I'm trying to conditionally specify the HTTP response code of one of my routes, given the result of my houdini-query.

more specifically, if my query can't find certain content, I'd like to return a `404`

The kit-way to do this is via calling `error/redirect` or returning nothing in `load`.
Seems like I can still do that via houdini's `onLoad` (great), however I can't find access to my query data at this `load` stage of the lifecycle.

So I'd like to suggest access to query data in the `onLoad` hooks? does that make sense?

illustration of what i'd like to do.
```svelte
<script context="module" lang="ts">
  export function MyQueryVariables({ page: { params: { foo } } }): MyQuery$input {
    return { foo }
  }

  export function onLoad(){
    let myData: MyQuery = ...
    if (!myData.thing) {
      this.error(404)
    }
    ...
  }
</script>


<script lang="ts">
  import { query, graphql, MyQuery } from '$houdini'

  const { data } = query<MyQuery>(graphql`
    query MyQuery($foo: String!) {
      thing(foo: $foo) {
        ...
      }
    }
  `)
</script>
```

I hope I'm not misguided. Thanks for a stellar tool, you rock.

I'd be happy to work on this. I've found the code for the `onLoad` logic but I would need to find access to the query results from there.

**Comment by AlecAivazis** [comment]
oh! that seems like a totally reasonable request - any ideas on what the api could look like? We would need to be able to support multiple `query`s in a single component so maybe something like this?

```
export function onLoad({data}) {
    const result = data.MyQuery
}
```

**Comment by ximus** [comment]
@AlecAivazis i jumped the gun and created https://github.com/AlecAivazis/houdini/pull/207 following your suggestion. Couldn't think of a preferred alternative.
