### ISSUE TITLE
Failed to resolve import "$houdini" from "src/routes/__layout.svelte". Does the file exist?

### ISSUE THREAD

**Issue by SorenHolstHansen** [AlecAivazis/houdini#220]
I am having issues using houdini in a monorepo.

My setup is this (everything is typescript)
```
apps/
  admin/         <- sveltekit app
  ...
packages/
  ... <- various packages used in the apps
package.json
```
And up until now, it has worked great. But now I am trying to add houdini to admin, and have followed the steps in the readme, and when I then start the app i get
```
Failed to resolve import "$houdini" from "src/routes/__layout.svelte". Does the file exist?
```

I am not sure whether this is because of houdini or because of my typescript configuration, but I thought you would maybe have an idea.

I tried doing the same stuff in a non-monorepo sveltekit app, and that worked fine, so i think the issues are with the monorepo.

My `tsconfig.json`in admin is
```
{
	"compilerOptions": {
		"moduleResolution": "node",
		"module": "es2020",
		"lib": ["es2020", "DOM"],
		"outDir": "./dist",
		"target": "es2020",
		/**
			svelte-preprocess cannot figure out whether you have a value or a type, so tell TypeScript
			to enforce using \`import type\` instead of \`import\` for Types.
			*/
		"importsNotUsedAsValues": "error",
		"isolatedModules": true,
		"resolveJsonModule": true,
		/**
			To have warnings/errors of the Svelte compiler at the correct position,
			enable source maps by default.
			*/
		"sourceMap": true,
		"esModuleInterop": true,
		"skipLibCheck": true,
		"forceConsistentCasingInFileNames": true,
		"baseUrl": ".",
		"allowJs": true,
		"checkJs": true,
		"paths": {
			"$lib": ["src/lib"],
			"$lib/*": ["src/lib/*"]
		}
	},
	"include": ["src/**/*.d.ts", "src/**/*.js", "src/**/*.ts", "src/**/*.svelte"]
}
```
But i have also tried putting houdini in the paths in various ways, but with no success.

Do you have an idea what could be wrong?

**Comment by AlecAivazis** [comment]
Hey @SorenHolstHansen - sorry you are running into some issues. If you want a project to compare with, this repo is a monorepo so you might be able to spot some differences.

Do you have a repo I can pull down to try?

**Comment by SorenHolstHansen** [comment]
Okay it suddenly started working?! The only thing i changed was add the CORS policy on the backend, so maybe that has something to do with it?
