### ISSUE TITLE
Info about native types?

### ISSUE THREAD

**Issue by colllin** [AlecAivazis/houdini#235]
Hi! How can I learn more about Houdini's native type mappings, e.g. how do I send the correct data type for the generated `timestamptz` scalar type that maps to a pg `timestamp` column?

**Comment by colllin** [comment]
That was dumb, sorry.  Apparently I created the `timestamptz` type to map a `moment` variable to an ISO string. 🥇

**Comment by AlecAivazis** [comment]
No problem at all! Happy to hear you got it settled :)
