### ISSUE TITLE
Support for subscriptions

### ISSUE THREAD

**Issue by plunkettscott** [AlecAivazis/houdini#50]
This is a super cool package and I love the idea of using the preprocess step. Genius!

I was curious if subscription support is planned. Is there a roadmap of features you'd like to have that I can refer to for these types of questions?

**Comment by AlecAivazis** [comment]
hey @plunkettscott! Thanks for the kind words.

Subscriptions are **definitely** on the roadmap for this project. I think the implementation is largely the same as mutations so its mostly a question of the API. We should be able to support situations where a subscription is acting like a live query relatively quickly but i haven't put in much thought for how to support users who want a more event-based approach.

**Comment by plunkettscott** [comment]
Thanks, @AlecAivazis! I'll give this a try ASAP.

**Comment by AlecAivazis** [comment]
Oh great! I would have tagged you on the PR if I had known. Please let me know if you run into any problems 👍
