### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by AlecAivazis** [AlecAivazis/houdini#55]
I'm not quite sure what the API should look like, but there should be some kind of support for interacting with connections that have the usual pagination args.

**Comment by pixelmund** [comment]
I think pagination is an important thing for any kind of application, would be great if this could be the next big thing on the Roadmap once sveltekit support is merged. I would like to help out but I don't really know where to start and am to unfamiliar with the code base. Thank you for your work Alec.

**Comment by AlecAivazis** [comment]
Hey @pixelmund! I appreciate your offer to help with the library. This project is clearly resonating with people and I could really use some help to build this in a sustainable way. #65 cleaned up a lot of tech debt that I have been meaning to address so I suggest waiting until that goes in before diving too deep in the code. The overall architecture is the same but things have shifted around a little.

All that being said, I think pagination is definitely a good candidate for the next big thing to add to houdini. The implementation is going to touch a lot of things but if that doesn't worry you, I would love to provide any direction you need. I think a good first step for this would be to agree on what the API looks like. Currently houdini uses `@connection` to mark any list that can be mutated however this could be very confusing to people coming from relay which uses `@connection` for pagination. Also a simple list does not satisfy the [connection spec](https://relay.dev/graphql/connections.htm) that users will run into while googling things so I think a strong argument could be made for changing `@connection` to something like `@list`.  I would love to be able to keep support for non-connection lists so I think my suggestion would be to treat `@connection` as an abstraction over `@list` (or whatever we decide to call it, definitely open to suggestions). 

What do you think? Any thoughts on the name of the directive or general API? It would probably be a good idea for us to look at how the big graphql libraries structure their API and see what we want to borrow from them.

I think a good next step for me after #65 is to document the internals somewhere to provide you and any one else an introduction to the overall architecture. My hope is that it would provide some clarity for how something like `@connection` could function within the codebase.  If you want some coding things to do while I'm putting that together, the `@connection` stuff in the `kit` branch should be pretty stable and hopefully the comments can guide you enough.

I apologize for the wall of text, just excited someone else wants to help 😄

**Comment by AlecAivazis** [comment]
Started thinking through these details a bit more. Going to use this post as a brain dump of my thoughts and various notes I want to keep

- `@connection` needs to be renamed to `@list` it really tags list fields as potential targets for the mutation fragments
    - `@paginated` (name still tbd) is syntactic sugar for `@list` on the appropriate field
- Regardless of cursor or offset based pagination, the component API should be the same. These functions should be returned from `fragment` or `query` if there is 
    - `loadNextPage(pageSize?: number)`/ `loadNextPage(pageSize?: number)`
    - `hasNextPage` / `hasPreviousPage`
   


From the [connection spec](https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo.Fields): 
 > hasPreviousPage is only meaningful when last is included, as it is always false otherwise. hasNextPage is only meaningful when first is included, as it is always false otherwise. When both first and last are included, both of the fields are set according to the above algorithms, but their meaning as it relates to pagination becomes unclear. This is among the reasons that pagination with both first and last is discouraged.
