### ISSUE TITLE
Custom scalars

### ISSUE THREAD

**Issue by AlecAivazis** [AlecAivazis/houdini#56]
Houdini needs a way to specify how to marshal/unmarshal scalars found in documents

**Comment by AlecAivazis** [comment]
I'm trying to come up with the right API for this. In general, the user needs to provide a few pieces of information:

- A function to massage the API's response into the corresponding javascript type 
- The corresponding typescript type (so generated type definitions can have the correct types)

This information needs to be made available in a way that both the generate function and the runtime have access to. Ideally it would also be portable enough for a third-party package to provide common types. I played around with having it embedded in the config file, however that would prevent things modules like `path` from being imported  as well as global objects like `process.env` from being accessed. The first is not such a big deal - the only bit of config that currently uses `path` is `schemaPath` which could easily be changed into a string denoting a relative path. However, the second limitation is much bigger since it would prevent any kind of switch for config values like `static`.

**Comment by AlecAivazis** [comment]
I've started this work in the [custom-scalars branch](https://github.com/AlecAivazis/houdini/tree/custom-scalars). Here is the API I am putting in place:

```typescript
// houdini.config.js

export default {
	// ...

	scalars: {
		// the name of the scalar we are configuring
		DateTime: {
			// the corresponding typescript type (what the typedef generator leaves behind in the response and operation inputs) 
			type: 'Date',
			// turn the api's response into that type
			unmarshal(val) {
				const date = new Date(0)
				date.setMilliseconds(val)

				return date
			},
			// turn the value into something the API can use
			marshal(date) {
				return date.getTime()
			},
		},
	},
}
```

**Comment by mdugue** [comment]
hey @AlecAivazis , thanks a lot for you work on this topic. 

I am wondering: is there a way to define complex scalar types? And maybe even some that are imported from a third party library? Such as 

```typescript
import {MyDate} from "my-date-library"

export default {
  scalars: {
    DateTime: {
      // ❌ this does not seem to work
      type: MyDate,

      unmarshal(val) { /* ... */},
      marshal(date) { /* ... */},
    },
  },
}
```

**Comment by mdugue** [comment]
@jycouet @AlecAivazis are you interested in a PR for the docs?

**Comment by jycouet** [comment]
It's always good to improve the doc yes 👍.
You can probably suggest something and we tweak it before merging if needed 🎉
