### ISSUE TITLE
Does not work with latest Sveltekit anymore

### ISSUE THREAD

**Issue by djmaze** [AlecAivazis/houdini#59]
In the latest sveltekit, there seem to have been several changes. There is no client.js or server.js anymore. Also, the svelte config is different and snowpack has been replaced by vite.

**Comment by djmaze** [comment]
I am not sure that effort is worthwhile. While it is not yet released, Sveltekit is a moving target. And I read somewhere that it might be going beta (and thus open source) in the coming days, so maybe wait a bit?

**Comment by AlecAivazis** [comment]
Yea i think you're right, there's plenty of stuff to work on while sveltekit stabilizes 👍

**Comment by georgecrawford** [comment]
SvelteKit is now in public beta. I’m so interested in using this library if I can. I wondered if @AlecAivazis plans to work on migrating as discussed above? If not, I could try, but it’ll be a steep learning curve!

**Comment by AlecAivazis** [comment]
hey @georgecrawford! If you are up to the task, I'm definitely open to walk you through the necessary bits! I'm eager to get more people working on the project so let me know if you're interested :)

**Comment by AlecAivazis** [comment]
I started working on supporting Sveltekit, hopefully will have something that works this weekend. I'll keep yall posted!

**Comment by georgecrawford** [comment]
Great! Sorry, I haven’t had a second to look into this yet. Fingers crossed it’s not too complex to integrate. 

________________



George

**Comment by AlecAivazis** [comment]
Alright, I think I have the necessary bits in place if anyone is interested: #65 

I should have this merged soon. Thanks for being patient yall!
