### ISSUE TITLE
Compile step failing with "require() of ES Modules not supported" error [Svelte Kit]

### ISSUE THREAD

**Issue by thormuller** [AlecAivazis/houdini#68]
I believe I followed the setup steps to the letter, but I'm hoping this issue is something straightforward that I'm missing.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: <PATH>/houdini.config.js
require() of ES modules is not supported.
require() of <PATH>/houdini.config.js from <PATH>/node_modules/houdini-common/build/cjs/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename houdini.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from <PATH>/package.json.
```

FYI, If I remove the "type":"module" line from package.json it errors out with `Cannot use import statement outside a module` related to the line in houdini.config: `import path from 'path'`

**Comment by thormuller** [comment]
I see

**Comment by AlecAivazis** [comment]
Welp, this was inevitable. 

It looks like your setup is using the common-js version of `houdini-common` even tho you are presumably bundling from SvelteKit's vite setup.  What version of node are you using? Do you mind pushing up your repo so I can poke around? In my testing, the bundler was able to pull in the correct version - could you try building the example and see if you run into the same problem?

**Comment by thormuller** [comment]
Thanks for the quick response! I'm on Node v14.16.1.

I'll try building the example as you suggest and see if there's something I missed that may have led to the errand version of houdini.common. I'm also happy to share my repo but I'm not sure the best convention is for doing this. Should I clone the branch and share it with you on a separate repo?

**Comment by AlecAivazis** [comment]
I don't think you missed anything in the instructions. In order to serve `esm` and `cjs` files side by side the packages rely on an [`exports` field](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini-common/package.json#L7) in the `package.json` file. My hunch is that your version of node doesn't support this - would you be able to upgrade to the latest version and try again? You can use something like `nvm` to do it in a reversible way.

re the best way to share: the easiest option is probably just to push it up as a new repo and send the link. I can pull it down and poke around without having to do anything too crazy

**Comment by AlecAivazis** [comment]
I pulled down your repo and reproduced the error so we know its not a problem with `node`, i'm going to see if I can figure out what's different between your setup and the example

**Comment by thormuller** [comment]
Thanks! I'm very curious now.

**Comment by pixelmund** [comment]
Im getting the same error.

```bash
Trying to load configs for /Users/js/Documents/giraphql
(node:27921) ExperimentalWarning: The ESM module loader is experimental.
Error while loading config
file:///Users/js/Documents/giraphql/node_modules/houdini-preprocess/build/esm/index.js:6
import { CompiledFragmentKind, CompiledQueryKind, CompiledMutationKind, CompiledSubscriptionKind } from 'houdini';
                               ^^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'houdini' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'houdini';
const { CompiledFragmentKind, CompiledQueryKind, CompiledMutationKind, CompiledSubscriptionKind } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:136:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
    at async ConfigLoader.loadConfig (/Users/js/.vscode/extensions/svelte.svelte-vscode-104.12.1/node_modules/svelte-language-server/dist/src/lib/documents/configLoader.js:117:33)
Found svelte.config.js but there was an error loading it. Using https://github.com/sveltejs/svelte-preprocess as fallback
Using svelte-preprocess v4.7.3 from /Users/js/Documents/giraphql/node_modules/svelte-preprocess
```

Don't know if this is related but it seems like the svelte vscode extension is unable to load the config, maybe this happens in vite too but the error gets swallowed?

**Comment by AlecAivazis** [comment]
I think I have a guess why this is happening - the binary is published as a commonjs module which is forcing vite to load the `cjs` version of `houdini-common` which is unable to import the `esm` config file since typescript compiled `imports` to `require`. 

I'm about to publish a new version of  the `@kit` tag that with the binary as an esmodule. Hopefully ill have something for you to test soon

**Comment by pixelmund** [comment]
Ah yeah, that makes sense.

**Comment by AlecAivazis** [comment]
Alright, I just pulled down `0.5.1-kit.5` into a fresh svelkit project and was able to run the binary. Mind giving that a try?

Thanks for being patient, this whole jump from `cjs` to `esm` has been a lot to wrangle.

**Comment by pixelmund** [comment]
Can you provide me a repo that i can pull, tried to setup a fresh kit project and used the api from your example. The generate command is working fine now. But i can't start the dev server because of:

```bash
Malformed svelte.config.js
file:///Users/js/Documents/houdini-test/node_modules/houdini-preprocess/build/esm/index.js:6
import { CompiledFragmentKind, CompiledQueryKind, CompiledMutationKind, CompiledSubscriptionKind } from 'houdini';
         ^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'houdini' does not provide an export named 'CompiledFragmentKind'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:121:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:171:5)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async load_config (file:///Users/js/Documents/houdini-test/node_modules/@sveltejs/kit/dist/cli.js:464:17)
    at async get_config (file:///Users/js/Documents/houdini-test/node_modules/@sveltejs/kit/dist/cli.js:519:10)
    at async file:///Users/js/Documents/houdini-test/node_modules/@sveltejs/kit/dist/cli.js:577:18
```

My package.json:

```bash
{
  "name": "~TODO~",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "preview": "svelte-kit preview",
    "generate": "houdini generate",
    "api": "node api.cjs"
  },
  "devDependencies": {
    "@sveltejs/kit": "next",
    "graphql": "15.5.0",
    "houdini": "^0.5.1-kit.5",
    "houdini-preprocess": "^0.5.1-kit.5",
    "svelte": "^3.34.0",
    "svelte-preprocess": "^4.0.0",
    "tslib": "^2.0.0",
    "typescript": "^4.0.0"
  },
  "type": "module",
  "dependencies": {
    "@fontsource/fira-mono": "^4.2.2",
    "@lukeed/uuid": "^2.0.0",
    "apollo-server": "^2.24.0",
    "cookie": "^0.4.1",
    "subscriptions-transport-ws": "^0.9.18"
  }
}

```

**Comment by AlecAivazis** [comment]
@pixelmund you were right, the pre-processor was still having trouble loading values from `houdini`. I fixed the problem and updated `@kit`. Here is a repo with the updated version: https://github.com/AlecAivazis/hello-houdini

**Comment by pixelmund** [comment]
@AlecAivazis Tested and can confirm it works!

**Comment by thormuller** [comment]
I can also confirm that this fixes the error on compile. Thanks all! Looking forward to making a success of Houdini--it's great to see a Svelte-native Graphql client.

**Comment by pixelmund** [comment]
I think time is near to tell the svelte discord  `showcase` that houdini now has sveltekit support to get some more attention to the project. That's where i found out about it.

**Comment by AlecAivazis** [comment]
@pixelmund i think you're right, however I would like to verify that the current version of `@next` supports sapper before we do that just so to avoid any issues we can see coming.

I'm currently running into a nasty hurdle in the integration - `jest` doesn't seem to allow the use of `import.meta.url` so i'm going to have to figure out some workaround for the test suite before #69 can go in
