### ISSUE TITLE
schema.graphql support

### ISSUE THREAD

**Issue by outerlook** [AlecAivazis/houdini#71]
Hi!

Along with support for `.json` schemas, will there be support for `.graphql` schemas?

**Comment by AlecAivazis** [comment]
Absolutely! If you have the time to give it a shot that would be great - the schema loading logic lives [here](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini-common/src/config.ts#L45). Should be relatively straight forward to check the filepath's extension and call the right function from `graphql-js`

**Comment by outerlook** [comment]
Alright! I'll try it in about 8 hours. Thanks!

**Comment by AlecAivazis** [comment]
Closing this since #77 went in
