### ISSUE TITLE
When lang='ts' is getting `unexpected token ' in JSON...` error

### ISSUE THREAD

**Issue by outerlook** [AlecAivazis/houdini#73]
Hi!

When a svelte file has `lang='ts'` instead of `lang="ts"`, it is getting:
`
SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
`

`JSON.parse("'ts'")` produces error, but
`JSON.parse('"ts"')` don't
 

[here it happens](https://github.com/AlecAivazis/houdini/blob/a6b1d6fe815095344b8c6c263b735b4b6adef2c4/packages/houdini-common/src/parse.ts#L112)

**Comment by pixelmund** [comment]
@outerlook im using lang="ts" just fine, did you add the preprocessor after svelte-preprocess like so `[sveltePreprocess(), houdini()]` ?

**Comment by AlecAivazis** [comment]
@outerlook - thanks for opening this up. Do you have the time to open a PR with a fix?

**Comment by outerlook** [comment]
Yes, I have, i will drop a PR

**Comment by AlecAivazis** [comment]
Closing this since #83 has been merged
