### ISSUE TITLE
How can i update the generated schema.json?

### ISSUE THREAD

**Issue by pixelmund** [AlecAivazis/houdini#76]
Hey im currently playing around with houdini, trying mutations etc. and learning stuff but it seems like the schema.json doesn't get updated when i run generate? Does houdini currently offer a way to update the schema? Or do i have to update it myself?

I could probably create a pull request in the next days, lets say we pass `--pull` to the generate command to pull the newest schema before generating?

**Comment by AlecAivazis** [comment]
At the moment, you have to update it yourself but I think adding `--pull-schema` to generate sounds like a great improvement. My original hunch was that it should be a separate command but its inevitable that they would just run `generate` after so we might as well do it all in one step. nice!
