### ISSUE TITLE
How to convert scalar types like JSONB and numeric 

### ISSUE THREAD

**Issue by thormuller** [AlecAivazis/houdini#78]
I'm getting errors on a few fields that are not one of the standard types when I use them in queries. Is there a recommended best way to handle the translation of extended types to types that Houdini can deal with?

`Error: Could not convert scalar type: jsonb`
`Error: Could not convert scalar type: numeric`

**Comment by AlecAivazis** [comment]
Hey @thormuller! Thanks again for opening an issue.

Unfortunately, houdini doesn't have any support for custom scalars. If you have any ideas for what supporting them could look like, please add them to #56.  

I'm going to close this issue to keep things tidy. If you are interested / have the time to add support for them, please let me know. I'd love to provide any guidance you need
