### ISSUE TITLE
Getting "Cannot convert undefined or null" errors on queries after upgrading to latest release

### ISSUE THREAD

**Issue by thormuller** [AlecAivazis/houdini#79]
I was on the 0.5.1-kit.5 release previously and my primary queries were working (though I was still struggling with subscriptions). I upgraded to latest, regenerated the schema, and now I am getting the following error, even after simplifying my schema to a single test query. 

```
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Cache._write (/$houdini/runtime/cache/cache.js:232:45)
    at Cache.write (/$houdini/runtime/cache/cache.js:19:14)
    at Object.writeData (/$houdini/runtime/query.js:58:19)
    at index.svelte:60:35
    at Object.$$render (<PATH>/node_modules/svelte/internal/index.js:1380:22)
    at Object.default (root.svelte:33:46)
    at eval (<PATH>src/routes/__layout.svelte:44:36)
    at Object.$$render (<PATH>/node_modules/svelte/internal/index.js:1380:22)
    at root.svelte:31:44
```

**Comment by AlecAivazis** [comment]
@thormuller is this the same repo as before? I suspect this is more problems with the cjs/esm interop. If you push up your changes I can take another look.

**Comment by thormuller** [comment]
Just shared. I'm happy to rollback if you recommend it. I was hoping the wall I was hitting with subscriptions would be helped by the update, but alas :)

**Comment by AlecAivazis** [comment]
I think there is a problem with the repo you invited me to - i dont see a `__layout` that sets the environment

**Comment by thormuller** [comment]
yep. Sorry about that. Missing files are up there now :)

**Comment by AlecAivazis** [comment]
np! I'm now having trouble getting past the opening page. It's asking me to log in but timing out when interacting with the auth emulator

**Comment by thormuller** [comment]
Right, it's looking for the Firebase auth emulator--do you have this on? Interestingly, I'm now having a CORS auth issue with the Hasura Graphql endpoint, which I wasn't having before the update.

**Comment by AlecAivazis** [comment]
Alright, I just removed the auth check and reproduced your error. It seems that you are running into the following error: `{ path: '$', error: 'resource does not exist', code: 'not-found' }`

**Comment by thormuller** [comment]
as in the graphql resource does not exist?

**Comment by AlecAivazis** [comment]
yea, i think its just because the `uid` is getting set to undefined. 

If you could add a log of the [document arg](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini/runtime/query.ts#L10) passed to `query` in your runtime, we should get a better sense of whats going on.

**Comment by thormuller** [comment]
I wonder if it is this CORS policy issue. It wasn't showing before until I logged out.

**Comment by thormuller** [comment]
ah

> yea, i think its just because the `uid` is getting set to undefined.
> 
> If you could add a log of the [document arg](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini/runtime/query.ts#L10) passed to `query` in your runtime, we should get a better sense of whats going on.

Makes sense. I'll give a try.

**Comment by thormuller** [comment]
It is passing the uid.

**Comment by AlecAivazis** [comment]
Are you seeing the same error logged that I am? What's happening is that the server isn't responding with a `data` field so the preprocessor is trying to write `undefined`, causing the problem. I'm adding some better error messages so this is less confusing in the future but we still need to figure out why you aren't getting `data` back (assuming i'm right)

**Comment by thormuller** [comment]
The error I'm seeing is `Cannot convert undefined or null to object`

I simplified the query to use no variables but same result.

**Comment by AlecAivazis** [comment]
Did you add a log of the document in the query runtime? Just to be clear, I updated `$houdini/runtime/query.js` to look like the following: 
![image](https://user-images.githubusercontent.com/916317/119456077-22ae8380-bcef-11eb-8855-da63c4875c84.png)

And see the following object logged: `{ path: '$', error: 'resource does not exist', code: 'not-found' }`. Can you please add that line and let me know what you see?

**Comment by thormuller** [comment]
I was just logging variables rather than document.initialValue, but either way I'm now seeing the error you're seeing. When I checked before I was seeing a value. Anyway, this seems like the problem. I just tried the variable as a hard coded value and it didn't pass through either

**Comment by AlecAivazis** [comment]
I just pushed up 7e9a90e which should do a better job at capturing this error before it gets to the cache. Will publish it up momentarily

**Comment by AlecAivazis** [comment]
Alright, its now up as `0.5.2`

**Comment by thormuller** [comment]
yes, already updated :)

**Comment by thormuller** [comment]
the updated error is showing now. should I be looking for anything else?

**Comment by thormuller** [comment]
If you think it's an issue in my code then yes, go ahead and close. I'm just not sure why the variable wouldn't be passing through anymore (including when I hard code the value). Nothing changed there since a week ago I presume?

**Comment by AlecAivazis** [comment]
I'll leave it open until we are certain :)

**Comment by thormuller** [comment]
Okay, I made a few changes, and I'm now running that log in runtime, but now it is successfully displaying the uid in rather than the error. However, the old "resource does not exist" error is still appearing on the page.

**Comment by AlecAivazis** [comment]
Just to make sure I'm following - the server still isn't responding with a `data` field in its response even though the variables are correct? If you log them in your environment do you see anything?

**Comment by AlecAivazis** [comment]
It might help if you can give me a valid `uid` that I can hard code to get past the auth issue. Would that be okay?

**Comment by thormuller** [comment]
i was a bit hasty with my previous note (thus I deleted it). I am not seeing any logging output from the runtime query now. I am able to confirm that there is a value assigned to the variable in the variables function. I also have tried removing the variable from the query altogether, same result.

A test uid is `7fb6faea-4cc8-4104-b56a-e8671c0983cf`

**Comment by AlecAivazis** [comment]
After hardcoding the value in the variables function to look like this:

![image](https://user-images.githubusercontent.com/916317/119461707-d1a18e00-bcf4-11eb-94ec-48a993d7bb78.png)

I updated `environment.js` to look like this:

![image](https://user-images.githubusercontent.com/916317/119461546-a7e86700-bcf4-11eb-805b-7db97f02a523.png)

and see the following logged:

![image](https://user-images.githubusercontent.com/916317/119461565-ae76de80-bcf4-11eb-975a-d41e724e4a7f.png)

To me, this says that the variable function is getting called and the results are being sent to the right place but there is a problem still with the server.

**Comment by thormuller** [comment]
okay. I'll focus on the server interaction. you can close this now. I'll let you know if I discover something relevant to the project. thanks!

**Comment by AlecAivazis** [comment]
sounds good! Sorry i can't be more help, without access to the server its hard to say what's going on

**Comment by thormuller** [comment]
You were very helpful--and I picked up some good tips for future debugging that I'll plan on sharing with others as this community grows. BTW, the issue was that in the environment.ts file the `https://` had been changed to `http://` when I adapted your example code. This was indeed causing server communication issues. Very stupid and obvious in retrospect. But at least now we'll know to check for this when we see this sort of error in the future. I owe you a very fancy cocktail (or equivalent).

**Comment by AlecAivazis** [comment]
Ahh nice catch!  I'm happy to hear that it was something that simple - would have been hard for me to go to sleep knowing there was an unresolved problem 😅 

Please let me know if you are still running into problems with subscriptions. There was a problem that got fixed in the `-8` version of the @kit tag. Hopefully things will work for you.
