### ISSUE TITLE
Subscription function documentation needs clarification

### ISSUE THREAD

**Issue by thormuller** [AlecAivazis/houdini#80]
Hi Alec, I've implemented the subscription to a point: it is receiving updates from the graphql server. I can observe the update being received in the console. However, when I attempt to use  the pattern in the example project the component is not updating--probably because my schema isn't similar enough for it to be intuitive.  I'd love to help refine the documentation but I need to get over the hump of understanding. I think part of the challenge is that you're using a very different pattern than the Apollo/React hook [https://hasura.io/learn/graphql/react/subscriptions/3-create-subscription/] that many of us are familiar with (naturally, as this is Svelte-optimized). I'm wondering if we can start with more of an analog to that simpler example to bridge the gap.

Let's say we have a graphql query just like you have it in the example project. It pulls a list of items like so:

```
const { data } = query<AllMyItems>(graphql`
     query AllMyItems($uid: ID!) {
          allItems: myItems(where: { uid: { _eq: $uid }, archived: { _eq: false } })
	       {
		    id
		    ...Card_item
	       }
          }
     `);
```

We list the results in generic Svelte form:
```
{#each $data.allItems as item (item.id)}
    <Card {item} />
{/each}
```

With Houdini, how can we create a subscription for the `allItems` list query instead of at the level of the component/fragment as you have it in the example? I want to do something like the following, but I'm not sure what the pattern is for connecting to the Houdini object/cache.

```
subscription(
  graphql`
	 subscription ItemUpdate($uid: ID!) {
	      myItems(where: { uid: { _eq: $uid } }) {
	          id
		  ...Card_item
              }
	  }
  `,
   {
         uid: $session.user.uid
   }
);
```

My best idea is to assign the outputs of the original query to a new svelte store and then update it when the subscription detects a change. But I'm not yet sure of how to access the updated values from the subscription function, as it doesn't work to treat it as a store.

**Comment by AlecAivazis** [comment]
Hey @thormuller!

Before we get too far, can you confirm that the subscription you have is returning a `data` field which is store whose value holds the most recent payload from the subscription? The cache should be storing and updating what it runs into but it won't know how to add them to another queries result.  One helpful debugging tip is to attach your cache to the `window` so you can see what's going on from your browser's console. Eventually, I'd love to add a UI to interact with the cache (similar to the [urql dev tools](https://github.com/FormidableLabs/urql-devtools/)) but for now, this is the easiest way to check what records and values are known by the cache.

It sounds like what you are looking for is a "live query", however subscriptions in GraphQL are much more akin to a traditional event system. In order to support a live query from a single subscription, the server should return the full list of items in the subscription payload and you should be able to just replace the top-level query with a subscription (although that will prevent the data from being loaded for SSR since the server doesn't open a socket connection). 

If you are looking for the payload of a subscription to be added to a query that's already triggered, you should be able to use same fragments from the 
 [connection mutation documentation](https://github.com/AlecAivazis/houdini#connections) in your subscription payload. 

If you are instead looking to collect all of the results in a single list as the events come through, you should be able to use a reactive statement to push the contents of the store onto a list in your component's local state.

**Comment by AlecAivazis** [comment]
Oh, can you also confirm that the artifact that was generated for your subscription has a `selection` field that references the fields in the `CardItem` fragment? I want to make sure you aren't getting bitten by the compiler trying to be too smart

**Comment by thormuller** [comment]
Here is my response. It has the payload/data and the items from the CardItem, though is that what you mean by `selection` field?
`"{"type":"data","id":"1","payload":{"data":{"allItems" : [{"id":"1ee4f35589430384d14b","title":"Mom&#39;s Kimchi ","klImages":"fe4f7814214fb7a15a9e498de8e17b3d.jpg"}]}}}`

In any case I agree with you, I'm thinking that observing the cache would be the next best step for zeroing in on the solution. Where would you recommend attaching it to window in the context of ssr?

(P.S. Love your idea of direct interaction with the cache)

**Comment by AlecAivazis** [comment]
Don't worry about the selection bit, we can go down that rabbit hole later if its necessary.

Also, before you start interacting with the cache directly, I'd like to confirm that the subscription function is behaving as it should. Could you add something like this to your component?

```
const { data } = subscription(...)

$: console.log($data)
```

And make sure that you are seeing values for data that you expect? It should start off as null and then get the value you showed above

**Comment by thormuller** [comment]
Alas, it is not updating the log after the initial null. I tried this test before and just figured I was missing something.

**Comment by AlecAivazis** [comment]
Great! I'm happy to hear that it's working as expected. I'm going to go ahead and close this issue but I think you do bring up a good point about documenting subscription patterns so I'll open up another to track that effort.

**Comment by thormuller** [comment]
Oh, how would you recommend logging the cache? I still think that would be helpful at this stage.

**Comment by AlecAivazis** [comment]
Ah yea sorry I forgot about that. The quickest way to do it is to import the cache directly in your `environment.ts` and inside of an `if (browser)` check, assign it to the window. It would look something like:

```javascript
import cache from '$houdini/runtime/cache'
import { browser } from '$app/env'

if (browser) {
    window.cache = cache
}
```  

Please keep in mind that the cache is not really ready for direct use and shouldn't be used for anything outside of debugging. If you find yourself needing to use it in your application logic, please let me know so we can see if there's a better approach. 
Probably worth mentioning that I definitely think the cache should usable in application logic, its just not there yet. In fact, I think mixing reactive statements with a programmatic cache API make for a very nice alternative to the updater functions that relay and apollo force on us so but until #58 goes in,  you should consider interacting with the cache as totally unstable. That api is likely to change unannounced

**Comment by thormuller** [comment]
Great explanation. Thanks! I have what I need now.

**Comment by vladimirdrayling** [comment]
how can I use subscriptions with ssr enabled?

I get the error:

```ts
6:57:18 PM [vite] Error when evaluating SSR module /src/environment.js:
Error: WebSocket implementation missing
    at Proxy.createClient (D:\dev\web\tests\todo\node_modules\graphql-ws\lib\client.js:76:15)
    at /src/environment.js:30:13
    at async instantiateModule (D:\dev\web\tests\todo\node_modules\vite\dist\node\chunks\dep-63d4bd14.js:75119:9)
6:57:18 PM [vite] Error when evaluating SSR module /src/lib/config.ts:
Error: WebSocket implementation missing
    at Proxy.createClient (D:\dev\web\tests\todo\node_modules\graphql-ws\lib\client.js:76:15)
    at /src/environment.js:30:13
    at async instantiateModule (D:\dev\web\tests\todo\node_modules\vite\dist\node\chunks\dep-63d4bd14.js:75119:9)
6:57:18 PM [vite] Error when evaluating SSR module /src/routes/__layout.svelte:
Error: WebSocket implementation missing
    at Proxy.createClient (D:\dev\web\tests\todo\node_modules\graphql-ws\lib\client.js:76:15)
    at /src/environment.js:30:13
    at async instantiateModule (D:\dev\web\tests\todo\node_modules\vite\dist\node\chunks\dep-63d4bd14.js:75119:9)
WebSocket implementation missing
Error: WebSocket implementation missing
    at Proxy.createClient (D:\dev\web\tests\todo\node_modules\graphql-ws\lib\client.js:76:15)
    at /src/environment.js:30:13
    at async instantiateModule (D:\dev\web\tests\todo\node_modules\vite\dist\node\chunks\dep-63d4bd14.js:75119:9)
```

### environment.js

```js
import { browser } from '$app/env';
import { Environment } from '$houdini';
import { createClient } from 'graphql-ws';

const ws = browser
	? createClient({
			url: 'wss://bu3ff.sse.codesandbox.io/graphql',
	  })
	: null;

console.log(ws);

export default new Environment(async function ({ text, variables = {} }) {
	// send the request to the api
	const result = await this.fetch('https://bu3ff.sse.codesandbox.io/graphql', {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json',
		},
		body: JSON.stringify({
			query: text,
			variables,
		}),
	});

	// parse the result as json
	return await result.json();
}, ws);
```

### svelte.config.js
```js
import houdini from 'houdini-preprocess';
import { resolve } from 'path';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: [houdini(), preprocess()],

	kit: {
		target: '#svelte',
		vite: {
			resolve: {
				alias: {
					$components: resolve('.', 'src', 'components'),
					$houdini: resolve('.', '$houdini'),
				},
			},
		},
	},
};

export default config;
```
