### ISSUE TITLE
Update Query response with subscription

### ISSUE THREAD

**Issue by thormuller** [AlecAivazis/houdini#82]
The following is an apparent bug in the way that the Houdini subscription function responds to certain events. 

I have a Query and a corresponding subscription set up to receive updates when a list of objects changes. I am observing the responses at both the websocket event level, and the Houdini cache level. In both these cases I see that the list updates as expected when properties on objects are changed, AND when objects are added or removed from the set.

However, the reactive value of { data } on the Query is **not** updating when items are added or removed, though it is when properties on objects are altered. 

I was unable to validate that this same behavior exists on the Example app due to an error I'm having with Apollo server locally, but this would be a natural place to confirm this is not specific to my project. To test this I would add and remove items on the database itself and confirm whether these changes are reflected on the SvelteKit page.

**Comment by AlecAivazis** [comment]
@thormuller thanks for opening this up. If i'm following your description correctly, I think the issue is that `subscription` is just holding onto the latest value is isn't actually subscribing to the cache. If so, this should be easy to fix but it might take me some time (i have a wedding today and a busy week ahead of me). 

If you want to try fixing this yourself, you can copy the way that [`query` subscribes to the cache](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini/runtime/query.ts#L47)

**Comment by thormuller** [comment]
@AlecAivazis No hurry on my end, go enjoy your wedding, etc. I might try to put that fix in, but otherwise I'll keep an eye out for a fix down the road.

**Comment by thormuller** [comment]
Oops, as I read over your suggestion more closely I realized I mis-titled this issue above which led to a misunderstanding. It's not the subscription function that is not updating in a reactive way, it's that the main Query results are not updating with new/deleted items via the subscription.  e.g., the `{ data } ` in the below f

```
const { data } = query<AllMyItems>(graphql`
		query AllMyItems($id: ID!) {
                      	    myItems({id: $id })
			}
		}
	`);
```
And then I have a subscription function with the same query that updates those values. I have a reactive statement like this `$: console.log($data.myItems)`  which updates with property change events, but which doesn't update with new/removed items from the list as described above.

**Comment by AlecAivazis** [comment]
Ahh okay so the runtime isn't going to know that a field on a subscription is the same as a field on a query and should be in sync. I think your best bet is to restructure your documents so that the subscription is triggered with a single new item instead of the full list. If you tag your query document with `@connection(name:"All_My_Items")` then you should be able to have something like this work as you want:

```graphql
subscription NewItem { 
    subscription NewItem { 
        ...All_My_Items_insert
    }
}
```

**Comment by thormuller** [comment]
FYI, I've implemented this approach and while it is updating the cache with database updates (including the @connection values exactly as expected), the reactive value in the main Query still does not update.  Here is my code:
 
![image](https://user-images.githubusercontent.com/395315/120122402-bfe14000-c165-11eb-9799-6270da880cfc.png)

Perhaps I'm just misunderstanding the logic of how the query document updates with the subscription values and cache, but I'm surprised it's not behaving consistently across the following situations:
• Successful reactive values upon updates to a list query when the changes are on fields inside records (full list subscription)
• No reactive values when the number of records on the list change (full list subscription)
• No reactive values for a list query after creation of a single new record on a list tagged @Connection (single item subscription)

I believe the Example app combines mutations with the subscription so I'm wondering if the subscription there works if changes are made exclusively on the server rather than via Houdini. If so, then I'll know the issue is something particular to my setup. I can do some more work to get the Example app running locally and test this.

**Comment by AlecAivazis** [comment]
I've been meaning to update the example to contain this exact use case. If you have the time to update it, that'd be awesome otherwise I'll try to get to it tonight.

In response to your three cases, the third "should work" and is the pattern I had in mind when designing the API. Once we have the example updated we can figure out where exactly the problem is. The second situation would be very hard to support without some kind of convention that says that a field on the subscription should update the query field. My hunch is that this pattern really only makes sense when trying to "preload" a value for a subscription. Given that, I think we would want to have some way of specifying this link instead of looking at the field names since the situation is complicated dramatically when there are arguments on the fields we are comparing. Another decorator maybe?

it's also probably worth mentioning that apollo has a [subscribeToMore](https://www.apollographql.com/docs/react/data/subscriptions/#subscribing-to-updates-for-a-query) fields on the response from a `query`. It would be pretty interesting to add this kind of feature to `queries` which could hide the details for linking a subscription and a query.

Until we have something like that in place, I think the best next step is to figure out why `All_Recipes_insert` isn't working.

**Comment by thormuller** [comment]
Agreed on the next step. I won't be able to do this tonight as I'm back in Amsterdam where it's already quite late, but will try tomorrow if you don't get to it. Many thanks.

**Comment by AlecAivazis** [comment]
I've updated the example to use a mutation fragment inside of the body of a subscription - it seems to be working just fine. Only real catch was to remove the mutation update so that I didn't duplicate the records in the list.

**Comment by thormuller** [comment]
I'm currently getting the following error when I try to run the Example app and when I try to run the Houdini init. This is immediately following pulling the latest code and running `npm install`. Note that I'm running the Apollo server and I've confirmed that the Apollo server is responding correctly to valid graphql requests via the /graphql endpoint. Is this a familiar issue?

`Unexpected token < in JSON at position 0
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (file:///Users/zola_admin/Documents/houdini/houdini-main/node_modules/@sveltejs/kit/dist/ssr.js:790:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestContext.fetchQuery (/Users/zola_admin/Documents/houdini/houdini-main/example/src/environment.ts:23:14)
    at async Module.fetchQuery (/$houdini/runtime/network.js:25:12)
`

Not that it's very helpful, but when I add logging to the query in environment.ts I get the following response:
```
Response {
  size: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      [Symbol(kCapture)]: false,
      [Symbol(kTransformState)]: [Object]
    },
    boundary: null,
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'http://localhost:4000/graphql',
    status: 404,
    statusText: 'Not Found',
    headers: {
      connection: 'close',
      'content-length': '147',
      'content-security-policy': "default-src 'none'",
      'content-type': 'text/html; charset=utf-8',
      date: 'Mon, 31 May 2021 12:35:53 GMT',
      'x-content-type-options': 'nosniff',
      'x-powered-by': 'Express'
    },
    counter: 0,
    highWaterMark: 16384
  }
}
```

**Comment by pixelmund** [comment]
@thormuller Can u show me your houdini config and your environment file? I pulled the example today and it worked without any issues, also you shouldn't have to run houdini init again if you are using the example? You can always run `houdini generate -p` to pull the latest schema.

**Comment by thormuller** [comment]
Thanks @pixelmund. Here are the files. Appreciate you giving this a quick look. 

![image](https://user-images.githubusercontent.com/395315/120199065-0e332500-c1e0-11eb-81e7-c892f2ed5ff0.png)

![image](https://user-images.githubusercontent.com/395315/120199197-391d7900-c1e0-11eb-89b4-2e03b6f16d6e.png)

**Comment by pixelmund** [comment]
Looks good to me, using the same and getting the response below. 
It's weird that you're hitting a 404.

Are you using the api provided by the example? 

```bash
Response {
  size: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null
    },
    boundary: null,
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'http://localhost:4000/graphql',
    status: 200,
    statusText: 'OK',
    headers: {
      'access-control-allow-origin': '*',
      connection: 'close',
      'content-length': '207',
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 31 May 2021 13:23:38 GMT',
      etag: 'W/"cf-LVVunDl19KGuW1YQCnjkjkyJkvI"'
    },
    counter: 0,
    highWaterMark: 16384
  }
}
```

**Comment by thormuller** [comment]
Yes, I'm just running the Apollo server as included. BTW, here are my exact steps:

And to be clear about my steps (which I just attempted again) that precede the error:
• cd to /Example
• `npm run api`
• `npm install` 
• `npx houdini generate` 
• `npm run dev`

**Comment by pixelmund** [comment]
Alright i will try to replicate your steps

**Comment by pixelmund** [comment]
Here are the steps that worked for me, i just tried it:

- clone repo
- cd example
- npm install
- npm run api
- Open new cmd tab
- cd example
- npx houdini generate
- npm run dev

**Comment by thormuller** [comment]
The bad news is that when replicating your steps I continued seeing the same issue. The GOOD news is that prompted by your validation that the issue was on my end I re-booted my machine and now it is working as expected. So thanks again for your help. I only wish we'd uncovered a more helpful tip for future users beyond "REBOOT YOUR MACHINE." Kinda lame as an output, but at least it works :)

**Comment by thormuller** [comment]
@AlecAivazis I've now confirmed that the item-level subscription works in the Example, so we should be good to close this issue. Once I get to a good resting place I'll review the documentation and may submit some doc clarifications to help future users, though I obviously hit a few snags that were particular to my local dev environment.

**Comment by AlecAivazis** [comment]
Awesome! I'm happy to hear we got to the bottom of this @thormuller - keep those issues coming! 

Thank you so much for verifying this works @pixelmund  ❤️
