### ISSUE TITLE
Support for SPA Mode

### ISSUE THREAD

**Issue by plunkettscott** [AlecAivazis/houdini#85]
Would supporting SvelteKit's [`adapter-static` SPA mode](https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode) be something you are willing to do? Currently the runtime does not work, expecting things like `document.initialValue` to be set but is not because there is no SSR hydration.

[Quite a few people](https://github.com/sveltejs/kit/issues/754), [myself included](https://github.com/sveltejs/kit/issues/754#issuecomment-819011031), embed the static assets into binaries we ship as part of the release process because we use languages that do not support SSR. In my case, that's embedding the assets in a Go application and serving them with an embedded file server.

Original SPA mode PR: https://github.com/sveltejs/kit/pull/1181

**Comment by AlecAivazis** [comment]
Yea that definitely seems like the kind of thing houdini should support. Unforunately, im not too familiar with the details of various adapters yet - any idea how we would be able to determine if we are running in spa mode? Now that the config file is a full on javascript file, we could always rely on a environment-based toggle if we have to 🤔 

I'm currently working on a branch for #72 and #67 which i think would handle the actual details for this as well - ill keep you up to date

**Comment by plunkettscott** [comment]
Thanks Alec! Trying to get a feel for the code base so that I can help out on some of these issues. Hoping I can get myself up-to-speed soon.

**Comment by AlecAivazis** [comment]
I absolutely agree that we want to avoid coupling to a particular adapter. The `query-outside-route` branch is taking a very similar approach to what you describe - if `query` encounters an undefined initial value for the query it loads it on mount (so that bare svelte apps and non route/layout components can get their data) however i'm not sure how to determine if kit will handle it or not. I'd like to avoid the extra network request if possible.

**Comment by plunkettscott** [comment]
Yeah, I can't think of a universal way to know that any framework (Sapper, SvelteKit) would handle the loading to avoid the network request.

I think there could be some automatic selection to be had from knowing the `mode` and then potentially reading the config file for the framework (for example, `svelte.config.js` has an `ssr` property in SvelteKit), but it makes assumptions about the configuration and I don't think that it's safe to be making those assumptions, especially with SvelteKit not yet at v1.

There's also the case where in SvelteKit someone can disable `ssr` on a specific page. I can't imagine a use case where you'd disable SSR for a single page and also be using houdini, but I'm sure someone will try it.

I think the only real way to know if SSR is happening by defauly is is to rely on an `ssr` configuration option in the `houdini.config.js` file.

**Comment by AlecAivazis** [comment]
@plunkettscott - i _think_ i have a working update to support the SPA mode. You'll have to add some logic in the config file to set the framework field to `svelte` when you are building the app in SPA mode but i think that's probably a necessary evil until we can figure out how to automatically detect it. 

Mind testing out #95 and see if it works for you?

**Comment by AlecAivazis** [comment]
With the release of `0.8.0`, I had to change the way that spa mode is handled. Now you have to keep `framework` set to `kit`, but set the `static` config value to `true`.
