### ISSUE TITLE
Accessing session on the client side receives the session store.

### ISSUE THREAD

**Issue by pixelmund** [AlecAivazis/houdini#86]
While implementing 'refetch queries' i noticed that the session passed to fetchQuery is a svelte store on the client side, it works fine in `load` which makes sense.
If you add this log to the example 
```typescript
async function fetchQuery({ text, variables = {} }, session: any) {
	console.log(session)

	const result = await this.fetch('http://' + API_URL, {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json',
		},
		body: JSON.stringify({
			query: text,
			variables,
		}),
	})

	// parse the result as json
	return await result.json()
}
```
You can see that session is `{subscribe: ƒ, set: ƒ, update: ƒ}`

We should probably use `get` from svelte/store in mutations and refetch.

**Comment by AlecAivazis** [comment]
Nice catch - i agree that we probably want to use `get` in those situations
