### ISSUE TITLE
Persisted Queries

### ISSUE THREAD

**Issue by pixelmund** [AlecAivazis/houdini#93]
I would like to discuss if we want to support persisted queries in the future. I like how relay handles it and personally i find them quite powerful in terms of security and saving bytes on network requests:

[https://relay.dev/docs/guides/persisted-queries/](https://relay.dev/docs/guides/persisted-queries/)

**Comment by AlecAivazis** [comment]
Its definitely something that I would love to see in `houdini`, just forgot to create the issue 😅

**Comment by pixelmund** [comment]
Thinking about this some more, we could probably use a relay like approach where we create a output file e.g. `queryMap.json` customizable with an cli flag `--persist-output ./src/some_folder/queryMap.json` with the artifact hash as `key` and the query as `value`. We could then pass the artifact or some form to the environments fetchFunction instead of only `text` and `variables`. From there some could simply pass `documentId` (the artifact hash) instead of the full query.

```ts
export default new Environment(async function (operation) {
	// send the request to the api
	const result = await this.fetch('/graphql', {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json',
		},
		body: JSON.stringify({
			// query: operation.text,
			variables: operation.variables,
                        documentId: operation.hash		
            }),
	})

	// parse the result as json
	return await result.json()
})

```

**Comment by AlecAivazis** [comment]
Awesome - in general the approach seems like the right one. I think it's probably more likely that the user is going to follow the standard that urql and apollo both follow which can be found [here](https://github.com/apollographql/apollo-link-persisted-queries#apollo-engine) but I don't think that really matters from our perspective. As long as a hash gets generated and attached to the artifact in a way that the environment has access to when making queries, the user can make that decision for themselves.

Also, `hashDocument` isn't used any more but I left it in the codebase in case we needed it. It's a remnant from when the preprocessor import the artifacts but that's no longer the case.
