### ISSUE TITLE
Filtering items with duplicate IDs on Insert

### ISSUE THREAD

**Issue by thormuller** [AlecAivazis/houdini#94]
**Situation**: A list of items is retrieved at load (Active_Items). A subscription fetches the latest item that appears on the server (NewItem). The Insert method within the Subscription adds the latest item to the list, BUT because the latest item is already included in the Active_Items list Svelte generates the following error:

`Error: Cannot have duplicate keys in a keyed each`

Alas, some Graphql server implementations don't provide an easy way to limit subscriptions only to mutate events so they'll start by pulling the latest item. Ideally the Insert method would filter out duplicate ids to avoid this issue.

Thoughts or suggestions? I can probably figure out a workaround with my graphl server (Dgraph) but thought I'd mention the challenge here.

**Comment by AlecAivazis** [comment]
If im following correctly, i think this is a side effect of your server-side subscription and therefor shouldn't be baked into the `insert` behavior. Another way to put that is that there is nothing inherently wrong with having the same entity show up twice in a list except that you are rendering it straight to a svelte component which doesn't like the duplicate key, if there was another way to generate a unique key, you wouldn't be running into this problem. 

I think the best solution is to not rely on the `_insert` fragment here and instead check if the node is already part of the connection and add it by hand if not. This relies on a having a stable imperative API for the cache which isn't completely ready yet (#58) but I'm pretty happy with the API for the bits you need so it should be relatively safe. I imagine this would look something like:

```javascript
const { data } = subscription(...)

$: {
    const currentConnection = [...cache.connection("Active_Items")].map(({id}) => id)
    if (!currentConnection.includes(data.item.id)) {
        cache.connection("Active_Items").append(data.item)
    }
}
```

**Comment by thormuller** [comment]
Thanks as always for a detailed and thoughtful response. These are perfectly reasonable approaches, and I certainly agree on avoiding extra complexity. I'll give your block a try and report back.

**Comment by thormuller** [comment]
When implementing the above, my attempt to append the new object to the cache connection is completely wiping the list instead of appending the object. The object values are the same

 I noticed that `append` requires 2-3 arguments. In looking through your tests, I see that you're including type definitions for the items. So I've added that as follows:

```
				cache.connection('Active_Items').append(
					{
						id: { type: 'ID', keyRaw: 'id' },
						title: { type: 'String', keyRaw: 'title' }
					},
					$data.queryNewItem
				);
```

$data.queryNewItem = `{id: "0x253ffaf03", title: "sample text"}`

Is there something else that needs to happen or be considered when appending items, or a debugging trick you've encountered when manually updating the cache? It's probably an error somewhere on my end, so that's on me, but perhaps this is a common symptom of something out of whack.

**Comment by AlecAivazis** [comment]
Ah damn, i probably should have looked at the tests first before writing that block. You are correct that you have to pass the schema information when appending the object.  This weekend is very busy for me so I don't know how  much time I'll have to dig into this but it might help to look at what happens when the runtime encounters the insert operation. [Here](https://github.com/AlecAivazis/houdini/blob/a6b1d6fe815095344b8c6c263b735b4b6adef2c4/packages/houdini/runtime/cache/cache.ts#L498-L508) is where that code lives. That block doesn't use `append` but if you look at append you'll see it's a [very thin wrapper](https://github.com/AlecAivazis/houdini/blob/a6b1d6fe815095344b8c6c263b735b4b6adef2c4/packages/houdini/runtime/cache/connection.ts#L64-L66) over that function.

**Comment by thormuller** [comment]
I'll start with that. Enjoy your weekend!

**Comment by AlecAivazis** [comment]
@thormuller i found some time to try this out in the example app and was able to get it working. Here's what i have for comparison:

```javascript


	const { data: sub } = subscription(graphql`
		subscription NewItem {
			newItem {
				item {
					id
					completed
					text
				}
			}
		}
	`)

	$: {
		if ($sub) {
			const existing = [...cache.connection('All_Items')].map(({ id }) => id)
			if (!existing.includes($sub.newItem.item.id)) {
				cache.connection('Filtered_Items').prepend(
					{
						id: {
							type: 'ID',
							keyRaw: 'id',
						},

						completed: {
							type: 'Boolean',
							keyRaw: 'completed',
						},

						text: {
							type: 'String',
							keyRaw: 'text',
						},
					},
					$sub.newItem.item
				)
			}
		}
	}
```

**Comment by thormuller** [comment]
Perfect. I was able to get this working. The key for debugging was examining the cache data entries to see that there was an issue with the new Root record created by the subscription update. What caused me confusion was seeing the new item in the cache while the $data result was not reflecting them. My conclusion is that the $data will be nulled if there are undefined variables in Root entries. 

For reference:

![image](https://user-images.githubusercontent.com/395315/121822409-326d1800-cc5c-11eb-8151-49ad48bca922.png)

**Comment by thormuller** [comment]
The code above works perfectly, the new items are added without issue. The problem remains that the while the cache values for the connection appear accurate (from what I understand of how the cache works) $data records for the initial query are reactively updated to null. So either the cache _isn't_ updating properly as it appears, or there's something I don't understand about how the $data object behaves from that initial Query that initiates the collection. I made a quick Loom video to make this crystal clear:

https://www.loom.com/share/be9c065908df40d5bf2a0865b0c80564

**Comment by AlecAivazis** [comment]
Well thank you for making the video! It definitely seems like strange behavior. It's strange that the example doesn't behave this way (i see the new records get added to the list). Today is a pretty busy day for me so I dont know if I'll have time to dive into this but you can try adding something similar to the example app to see if you are noticing the same behavior.

Oh, its also probably worth mentioning that along the way in putting together #95 I did encounter an issue which caused me to clean up a rather ugly part of the cache's implementation. You might want to try pulling that branch down and see if it fixes the problem (this is a guess on my part, it might not be related at all)

**Comment by thormuller** [comment]
Alas, updating to the latest code didn't fix the issue :( Would have been nice.

I also checked the Example and it is not showing similar behavior–it works as expected. This appears to be something outside the happy path triggering this weirdness.

**Comment by AlecAivazis** [comment]
Damn, well I suppose its good to hear that you were able to see things work with the example app. I suppose the next step is to figure out what about your application is off of the happy path. Let me know if you need any more guidance

**Comment by thormuller** [comment]
It seems like some it would help me to add logging in the right places where the Query value is updated after an update. If you could suggest a spot or two in the Houdini code where that happens that would be great.

**Comment by AlecAivazis** [comment]
@thormuller - that happens [here](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini/runtime/query.ts#L78)

**Comment by AlecAivazis** [comment]
I'm going to close this issue since I dont think there is anything actionable here - @thormuller please feel free to let me know if you still need help figuring out how your situation deviates from the happy path

**Comment by thormuller** [comment]
FYI, updating to the latest release `0.72` did fix resolve this issue.

**Comment by AlecAivazis** [comment]
fantastic! im very happy to hear that
