### ISSUE TITLE
`npm run watch` equivalent with SvelteKit

### ISSUE THREAD

**Issue by georgecrawford** [AlecAivazis/houdini#96]
Hi.

Thanks for this very interesting library. I'm having a play with it with Sveltekit. I'd love to work out how to achieve a `npm run watch` script which would detect changes to GraphQL query instructions in `.svelte` files, and would run `houdini generate` and then restart the sveltekit server (or, ideally, somehow inform Vite that the files have changed). 

It seems like it'd be simple, and indeed it mostly works with something like `chokidar` or `nodemon`, except that because Houdini seems to replace all the files in `$houdini`, rather than just the files which have changed, the sveltekit server restarts far too often.

I wonder if it's possible to improve the writing of files to only update the changed ones, or if you know of a solution to achieve the same effect?

**Comment by AlecAivazis** [comment]
Hey @georgecrawford!

This is something I'm definitely interested in. Atm running `generate` replaces the environment file in a way that vite really doesn't like so i frequently have to restart vite while working on the example. It's a big thorn in my side haha.

I think it would be a great improvement to the generation logic to see if the existing file matches what would be written and only update the necessary files - i just haven't gotten to it yet. If you wanted to try to add it, I'd love to review a PR.

**Comment by georgecrawford** [comment]
I could certainly take a look. Could you point me to the code locations from which the various files are written?

________________



George

**Comment by AlecAivazis** [comment]
Yea, absolutely! Anything that's generated from the compiler comes from [this directory](https://github.com/AlecAivazis/houdini/tree/main/packages/houdini/cmd/generators). At the moment, there are three things that are written to disk: the artifacts for the documents found in a project, the type definitions, and the runtime.

Let me know if you need any other guidance. Probably worth mentioning you can always reach out to me on the Svelte discord if you prefer chatting there.

**Comment by georgecrawford** [comment]
I’m not hugely familiar with lerna or yarn workspaces. Could you list the steps I need to run after cloning the repo to get the example working with the local version of houdini please? 

________________



George

**Comment by georgecrawford** [comment]
I've got houdini working from the local repo checkout - some combination of yarn and npm install, and npm link. So I'll take a look at only writing changed files now.

**Comment by georgecrawford** [comment]
@AlecAivazis This approach seems to work well for me. WDYT? https://github.com/AlecAivazis/houdini/pull/97

**Comment by georgecrawford** [comment]
PR was merged, thanks @AlecAivazis!
